variables:
  APP_NAME: "th2-recon"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "2"
  MAINTENANCE_VERSION: '59'
  BUILD_ENABLED: 'false'
  DOCKER_PUBLISH_ENABLED: 'false'
  PYPI_PUBLISH_ENABLED: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-python.yml'
