image: docker:19.03.8

services:
  - docker:19.03.8-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: $CI_REGISTRY/th2-recon
  VERSION: "1.1"

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
  - docker-in-docker
  stage: build
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest --tag $IMAGE_NAME:$VERSION.$CI_PIPELINE_IID --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$VERSION.$CI_PIPELINE_IID
    - docker push $IMAGE_NAME:latest
